Update quick_build.yml

diff --git a/.github/workflows/quick_build.yml b/.github/workflows/quick_build.yml
--- a/.github/workflows/quick_build.yml
+++ b/.github/workflows/quick_build.yml
@@ -12,7 +12,6 @@ on:
         default: DEV
         required: true
 
-    
 jobs:
   test:
     runs-on: ubuntu-latest
@@ -24,84 +23,107 @@ jobs:
         submodules: true
 
     - name: Install Build Packages
-      run: "sudo apt-get update && sudo apt-get install -y xsltproc hunspell pandoc"
-    # Get current banch name to use it as dest directory
-    - name: Extract branch name
-      shell: bash
-      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
-      id: extract_branch
+#      run: "sudo apt-get update && sudo apt-get install -y xsltproc hunspell pandoc"
+      run: "sudo apt-get update && sudo apt-get install -y xsltproc hunspell python3-lxml"
 
     - name: Install Jing
       run: wget -O - https://github.com/relaxng/jing-trang/releases/download/V20181222/jing-20181222.zip | jar -x
 
-
+    - name: Set branch name
+      run: echo "action_branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
+      
     - name: Quick Build
-      run: WARN_PATH="output/SanityChecksOutput.md" make release 
+      run: WARN_PATH="output/SanityChecksOutput.md" make
+
+      # PDFify
+    - name: PDFify
+      if: ${{ github.event_name == 'workflow_dispatch' }}
+      run: |
+        sudo apt-get install -y wkhtmltopdf xvfb
+        xvfb-run --auto-servernum --server-args='-screen 0, 1024x768x16' /usr/bin/wkhtmltopdf \
+          --enable-local-file-access --javascript-delay 15000 --footer-right '[page]' \
+          file://${PWD}/output/${PWD##*/}.html?expand=on \
+        output/${PWD##*/}-paged.pdf
+
 
     - id: validate
       run: |
         RNG_OUT="output/ValidationReport.txt" make validate || true
-        echo ::set-output name=VALERRORS::$(wc -l output/ValidationReport.txt | { read first rest ; echo $first ; } )
 
+    - name: Set valerrors
+      run: echo "action_valerrors=$(wc -l output/ValidationReport.txt | { read first rest ; echo $first ; } )" >> $GITHUB_ENV
+        
     - id: spellcheck
       run: |
         SPELL_OUT="output/SpellCheckReport.txt" make spellcheck
-        echo ::set-output name=LINES::$(wc -l output/SpellCheckReport.txt | { read first rest ; echo $first ; } )
 
+    - name: Set spellerrors
+      run: echo "action_spellerrors=$(wc -l output/SpellCheckReport.txt | { read first rest ; echo $first ; } )" >> $GITHUB_ENV
+
+    - name: Get Transforms Date
+#      run: echo "action_tdate=2002222" >> $GITHUB_ENV
+      run: echo "action_tdate=$(cd transforms && git log -1 --format=%cs; cd ->/dev/null)" >> $GITHUB_ENV
+
+    - name: Setup Java JDK
+      uses: actions/setup-java@v1.4.3
+      with:
+        java-version: 1.8
+        
+    - name: Get DaisyDiff
+      run: |
+        wget -O- https://github.com/AndroidKitKat/ExecuteDaisy/archive/master.zip | jar -x
+        [ -d "output/images" ] || mkdir "output/images";
+        cp -u -r ExecuteDaisy-master/js ExecuteDaisy-master/css output;
+        cp -u ExecuteDaisy-master/images/* output/images;
+
+      
+    - name: Make tmp dir
+      run: mkdir tmp
+      
     - name: diff
-      run: make diff || true; 
+      run: TMP=tmp make diff || true; 
     # Little diff depends on having a git history. 
     # The current checkout has  depth=1 and has no history
     #- name: little diff
     #  run: make little-diff || true
 
-    - name: Make a directory listing
-      run: >
-          cd output;
-          (echo "<html><head><title>Listing</title></head><body>";
-           date;
-           echo "<br/><ol>";
-           for aa in $(find . -name '*.*'); do
-                echo "<li><a href='$aa'>$aa</a></li>";
-           done;
-           echo "</ol></body></html>") > index.html
- 
-    - name: Deploy 🚀
-      uses: JamesIves/github-pages-deploy-action@4.0.0
-      with:
-        branch: gh-pages # The branch the action should deploy to.
-        folder: output # The folder the action should deploy.
+
+    - name: Outstanding TDs
+      id: tds
+      run: |
+        make effective
+        PP_XML=output/effective.xml RNG_OUT=output/TDValidationReport.txt make validate || true
+        if [ "${{steps.extract_branch.outputs.branch}}" == "master" ] &&
+           ls input/tds/*.xml ; then
+          echo "Master branch should not have TDs" >> output/TDValidationReport.txt
+        fi
+        if ls input/tds/*.xml; then
+           PP_XML=output/effective.xml PP_RELEASE_HTML=output/AppliedTDs.html make release
+           java -jar ExecuteDaisy-master/*.jar output/*-release.html output/AppliedTDs.html --file=output/AppliedTDs-Diff.html
+        fi
+
+
+    - name: Set TD badge attributes
+      run: |
+        echo "action_tdcolor=$(if [ -s output/TDValidationReport.txt ]; then echo orange; else echo green; fi)" >> $GITHUB_ENV
+        echo "action_tdwarns=$(wc -l output/TDValidationReport.txt | { read first rest ; echo $first;} )" >> $GITHUB_ENV
+        
+        
+    - name: Validate Effective
+      run: |
+        echo "action_tdcolor=$(if [ -s output/TDValidationReport.txt ]; then echo orange; else echo green; fi)" >> $GITHUB_ENV
+        echo "action_tdwarns=$(wc -l output/TDValidationReport.txt | { read first rest ; echo $first;} )"       >> $GITHUB_ENV
+
+
 
     - name: Prepare environment
-      id: coverage
       run: |
         # Generates a GitHub Workflow output named `lines` with a coverage value
-        echo "##[set-output name=spellcolor;]$(if [ 0 = ${{ steps.spellcheck.outputs.LINES }} ]; then echo green; else echo red; fi)"
-        echo "##[set-output name=valcolor;]$(if [ 0 = ${{ steps.validate.outputs.VALERRORS }} ]; then echo green; else echo red; fi)"
-
-        # Output values to be used by other steps
-        echo "##[set-output name=path;]${BADGE_PATH}"
-        echo "##[set-output name=branch;]${BRANCH}"
-      env:
-        BADGE_PATH: ${{ steps.extract_branch.outputs.branch }}/warnings-badge.svg
-        BRANCH: gh-pages
-
-    - name: Get Status
-      run: |
-         echo ::set-output name=WORD::$(if [ -s output/SanityChecksOutput.md ]; then echo some; else echo none; fi )
-         echo ::set-output name=COLOR::$(if [ -s output/SanityChecksOutput.md ]; then echo red; else echo green; fi )
-      id: status
-      
-
-    - uses: actions/checkout@v1
-      with:
-        ref: ${{ steps.coverage.outputs.branch }}
-
-    # Create the directory where badges will be saved, if needed
-    - name: Create destination directory
-      env:
-        BADGE_PATH: ${{ steps.coverage.outputs.path }}
-      run: mkdir -p "${BADGE_PATH%/*}"
+        echo "action_spellcolor=$(if [ 0 = ${{ env.action_spellerrors }} ]; then echo green; else echo red; fi)" >> $GITHUB_ENV
+        echo "action_valcolor=$(if [ 0 = ${{ env.action_valerrors }} ]; then echo green; else echo red; fi)" >> $GITHUB_ENV
+        echo "action_sanitystatus=$(if [ -s output/SanityChecksOutput.md ]; then echo some; else echo none; fi)"         >> $GITHUB_ENV
+        echo "action_sanitycolor=$(if [ -s output/SanityChecksOutput.md ]; then echo red; else echo green; fi )"         >> $GITHUB_ENV
+          
 
 
      # Use the output from the `coverage` step
@@ -109,56 +131,81 @@ jobs:
       uses: emibcn/badge-action@v1
       with:
         label: 'Misspellings'
-        status: ${{ steps.spellcheck.outputs.LINES }}
-        color: ${{ steps.coverage.outputs.spellcolor }}
-        path: ${{ steps.extract_branch.outputs.branch }}/spell-badge.svg
+        status: ${{ env.action_spellerrors }}
+        color: ${{ env.action_spellcolor }}
+        path: output/spell-badge.svg
 
      # Use the output from the `coverage` step
     - name: Generate the validation badge SVG image
       uses: emibcn/badge-action@v1
       with:
         label: 'Validation'
-        status: ${{ steps.validate.outputs.VALERRORS }}
-        color: ${{ steps.coverage.outputs.valcolor }}
-        path: ${{ steps.extract_branch.outputs.branch }}/validation.svg
+        status: ${{ env.action_valerrors }}
+        color: ${{ env.action_valcolor }}
+        path: output/validation.svg
 
-
-    - name: Upload badge as artifact
-      uses: actions/upload-artifact@v2
-      with:
-        name: badge
-        path: ${{ steps.extract_branch.outputs.branch }}/spell-badge.svg
-        if-no-files-found: error
 
    # Use the output from the `coverage` step
     - name: Generate the badge SVG image
       uses: emibcn/badge-action@v1
       with:
         label: 'Warnings'
-        status: ${{ steps.status.outputs.WORD }}
-        color: ${{ steps.status.outputs.COLOR }}
-        path: ${{ steps.coverage.outputs.path }}
+        status: ${{ env.action_sanitystatus }}
+        color: ${{ env.action_sanitycolor }}
+        path: output/warnings.svg
 
-    - name: Upload badge as artifact
-      uses: actions/upload-artifact@v2
+
+    - name: Generate the transforms badge
+      uses: emibcn/badge-action@v1
       with:
-        name: badge
-        path: ${{ steps.coverage.outputs.path }}
-        if-no-files-found: error
+        label: 'Transforms'
+        status: ${{ env.action_tdate }}
+        color: gray
+        path: output/transforms.svg
 
-    - name: Commit badges
-      continue-on-error: true
-      env:
-        BADGE: ${{ steps.coverage.outputs.path }}
+    - name: TD Badge
+      uses: emibcn/badge-action@v1
+      with:
+        label: 'TDs'
+        status: ${{ env.action_tdwarns }}
+        color:  ${{ env.action_tdcolor }}
+        path: output/tds.svg
+
+    - name:  Prepare checkout
       run: |
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add "${{ steps.extract_branch.outputs.branch }}"
-        git commit -m "Add/Update badges"
+        pwd
+        ls
+        echo "---"
+        mkdir gh-pages
 
-    - name: Push badge commit
-      uses: ad-m/github-push-action@master
-      if: ${{ success() }}
+    - uses: actions/checkout@v3
       with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        branch: ${{ steps.coverage.outputs.branch }}
+        ref: gh-pages
+        path: gh-pages
+
+    - name:  Move output to branch
+      run: |
+        pwd
+        ls
+        echo "+++"
+        rm -rf gh-pages/${{ env.action_branch }}
+        mv output gh-pages/${{ env.action_branch }}
+        
+    - name: Make listing
+      run: |
+        cd gh-pages
+        (echo "<html><head><title>Listing</title></head><body>";
+         date;
+         echo "<br/><ol>";
+         for aa in $(find . -name '*.*'); do
+            echo "<li><a href='$aa'>$aa</a></li>";
+         done;
+         echo "</ol></body></html>") > index.html
+        
+    - name: Deploy 🚀
+      uses: JamesIves/github-pages-deploy-action@4.0.0
+      with:
+        branch: gh-pages # The branch the action should deploy to.
+        folder: gh-pages # The folder the action should deploy.
+
+        
